filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log*"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

  #setup.dashboards.enabled: true
setup.kibana.host: "http://kibana:5601"
